/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111829-g3c9dc009b6-20230827"
#endif /* AVUTIL_FFVERSION_H */
